CREATE TABLE IF NOT EXISTS members(
	id 		BIGINT 	PRIMARY KEY AUTO_INCREMENT ,
	name 	VARCHAR NOT NULL,
	birth 	DATE 	NOT NULL,
	email 	VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS resumes(
	id 			BIGINT 		PRIMARY KEY AUTO_INCREMENT ,
	member_id 	INT 		NOT NULL,
	typ 		INT 		NOT NULL,
	ym 			DATE 		NOT NULL,
	content 	VARCHAR 	NOT NULL
);

ALTER TABLE resumes ADD FOREIGN KEY (member_id) REFERENCES members(id);

